### PR TITLE
Updated UUID and Yaml support

### PR DESCRIPTION
**Pull request by gpotter2**
Hey !

I hope it will be useful :)

I was using files i modified because i was thinking that the project was innactive...

Here there are :)

### CODE REVIEW

**Comment by 1Rogue** [comment]
Unfortuantely this PR breaks the maven packaging and introduces some new bugs to the code. I'll be overhauling with CodelanxLib and pushing out a completely new version of this plugin.

**Comment by gpotter2** [comment]
ok...

**Comment by gpotter2** [comment]
Anyway... Are you going to add your actual source to github, so we can help you to make it quicker ?
Cause it's quite long to developp....

:)

**Comment by 1Rogue** [comment]
Tell you what, I have to finish up some stuff this week for my job (I'm changing to a new one), however when I get the source to an error-free state then I can push it up and slate changes that still need to be made.

**Comment by gpotter2** [comment]
Great !
Thx :)

**Pull request closed without merging**
